### ISSUE TITLE
`gravatar-ui`- Screenshot testing

### ISSUE THREAD

**Issue by hamorillo** [Automattic/Gravatar-SDK-Android#114]
Review and try to implement **a stable** set of screenshot tests.

**Comment by Sissyken145** [comment]
![20240422_223254](https://github.com/Automattic/Gravatar-SDK-Android/assets/128193936/6c074878-0308-4591-b00e-fd451b6e0e6c)

**Comment by Sissyken145** [comment]
Such a beautiful picture

**Comment by hamorillo** [comment]
[EmergeTools](https://docs.emergetools.com/docs/snapshot-testing)
- ✅ You don't have to write any code if you have `@Preview` you have the test
- ❌ Looks really easy to set up. However, I'm having some issues in order to get it ready. I contact EmegeTools support.

I wanted to try it because it's great not to need to create specific code for the test. In the meantime, I'll continue with another approach.
