### ISSUE TITLE
Replace `enum class ErrorType` by a sealed class to add properties to errors

### ISSUE THREAD

**Issue by maxme** [Automattic/Gravatar-SDK-Android#12]

**Comment by eyedol** [comment]
@maxme is this up for grabs if so will be nice to flesh out a bit more or this sort of depends on the work needed by backend for #66 ?

**Comment by eyedol** [comment]
oh I was hoping to receive a response on it. If it's not ready then I'll wait.

**Comment by maxme** [comment]
Hey @eyedol sorry, I missed your previous comment. This one is a bit tricky as we don't know yet what property we'll add. Same as with #66 this is going to depend on the API changes. This ticket serves more of a reminder than a real task for now.

**Comment by eyedol** [comment]
No worries. This is also not ready then. Thanks for confirming it.

**Comment by AdamGrzybkowski** [comment]
@maxme Given that we will release a major version, do you think we should also tackle this one?
