### ISSUE TITLE
Things to check before releasing 1.0.0

### ISSUE THREAD

**Issue by maxme** [Automattic/Gravatar-SDK-Android#134]
- [x] Unify profile component names: ProfileCard / MiniProfileCard / LargeProfile / LargeProfileSummary.
 - [x] Network interface (coroutines vs. listeners or both).
 - [x] Support for the "real" endpoint `https://api.gravatar.com/v3/profiles/{id}` - #135
 - [x] Generic state management? `MiniProfileCard(state: State<UserProfile>)` vs. `MiniProfileCard(state: UserProfileState)` vs. `MiniProfileCard(userProfile: UserProfile, state: State)`
 - [x] Screenshot testing. - #114

**Comment by hamorillo** [comment]
- [x] Link the [Get Started](https://github.com/Automattic/Gravatar-SDK-Android/blob/trunk/docs/get-started/get-started.md) in the [README.md file](https://github.com/Automattic/Gravatar-SDK-Android/blob/trunk/README.md) - #169

**Comment by hamorillo** [comment]
[1.0.0](https://github.com/Automattic/Gravatar-SDK-Android/releases/tag/1.0.0) has been released! 🚀
