### ISSUE TITLE
Testing: Use fakeimages in screenshot tests

### ISSUE THREAD

**Issue by hamorillo** [Automattic/Gravatar-SDK-Android#233]
Coil has some documentation about how to use fake images in screenshots with Paparazzi. It could be interesting for us.

https://coil-kt.github.io/coil/testing/

**Comment by AdamGrzybkowski** [comment]
This was semi-implemented to fix flaky tests here https://github.com/Automattic/Gravatar-SDK-Android/pull/257. "Semi" because I didn't use real images just a plain background color instead.
