### ISSUE TITLE
Drop Result type in favor of kotlin.Result

### ISSUE THREAD

**Issue by AdamGrzybkowski** [Automattic/Gravatar-SDK-Android#296]
Gravata.Result type doesn't add anything extra and as per this [post](https://kotlinlang.org/docs/api-guidelines-simplicity.html#reuse-existing-concepts) this will reduce the mental complexity and shrink the size of our API.

**Comment by wzieba** [comment]
+1. When working with Gravatar SDK, it was confusing to understand this setup as I was confusing `com.gravatar.services.Result` with `kotlin.Result`

Additionally, the custom `Result` class prevents me from using some helpful methods like `fold`.

**Comment by AdamGrzybkowski** [comment]
As I was reading about the `Result` class I started doubting this is a good idea. As per [this design documment](https://github.com/Kotlin/KEEP/blob/master/proposals/stdlib/result.md#error-handling-style-and-exceptions):

> The Result class is designed to capture generic failures of Kotlin functions for their latter processing and should be used in general-purpose API like futures, etc, that deal with invocation of Kotlin code blocks and must be able to represent both a successful and a failed result of execution. The Result class is not designed to represent domain-specific error conditions.

That's not in line with what we do with our SDK. We try to provide users with domain-specific errors that are defined by `ErrorType`. Those might look generic for now, but we have more error types incoming in the new OpenAPI spec. 

Later on in the document:

>If there is a business need to distinguish different failures and process these different failures in distinct ways on each invocation site, then the following kind of signature shall be considered:

This seems to be our use case specifically. 

@wzieba thoughts on this?

**Comment by wzieba** [comment]
I see, thanks for diving into the design document. 

I'd still suggest doing something to distinguish a `Result` from Gravatar SDK vs. `Result` from Kotlin API. E.g. in the design document I can see an example: `FindUserResult` which is easy to understand just by looking at it (I see it's a domain-mapped result).

At the same time I understand you might not want to break API. But maybe something like

```
typelias GravatarResult = kotlin.Result
```

would work? I just try to find a way to reduce confusion for SDK consumers.

**Comment by wzieba** [comment]
I forgot to mention that I completely agree that we should follow the design document!

**Comment by AdamGrzybkowski** [comment]
>typelias GravatarResult = kotlin.Result

This won't help us though. We will still end up with a generic `Throwable` error type that is not enough for domain-specific errors, right?

**Comment by wzieba** [comment]
Sorry 🤦 I meant `typealias GravatarResult = com.gravatar.services.Result`.

**Comment by AdamGrzybkowski** [comment]
@maxme  @hamorillo any thoughts on this?

**Comment by hamorillo** [comment]
Thanks for the link to the design document! 

As you both pointed out, I don't think using `kotlin.Result` here is the best option.

> I'd still suggest doing something to distinguish a Result from Gravatar SDK vs. Result

Fair point. With current IDEs, I don't see it as a huge problem, but I agree it could confuse someone. Something like `GravatarNetworkResult` could have been better. 😖

With the `type alias`, we can minimize the confusion, but developers can still see the Result class. 🤔

Another option can be to refactor our class to something similar to `FindUserResult` in the design document, for example:

```
public sealed class GravatarNetworkResult<T> {

    public data class Success<T>(public val value: T) : GravatarNetworkResult<T>()
    public data object ServerError : GravatarNetworkResult<Nothing>()
    public data object RateLimitExceeded : GravatarNetworkResult<Nothing>()
    ...
}
```

However, I'm not sure if it simplifies or adds too much value at this point.

**Comment by AdamGrzybkowski** [comment]
Having each error type in a separate class would not provide much value over what we have now. I'm leaning towards renaming the `Result` -> `GravatarResult` for better autocompletion in the AS.
