### ISSUE TITLE
QuickEditor: Downsize uploaded image

### ISSUE THREAD

**Issue by AdamGrzybkowski** [Automattic/Gravatar-SDK-Android#305]
There's a bug in UCrop that cause the cropped images to keep their original file size. 

The [PR](https://github.com/Yalantis/uCrop/pull/926) with a fix is open but it seems unlikely we can get it merged.

**Comment by AdamGrzybkowski** [comment]
@maxme It looks like we will have to go with the fork. Do you want to use the WP one, or create a new one?

**Comment by maxme** [comment]
> Do you want to use the WP one, or create a new one?


The WP one is not used. WPAndroid uses the official version now (v2.2.9), the repo should be closed or deprecated. 

IMO we should create a new one, forking the official repo under the `automattic/` group. If we have to keep it, and eventually if WPAndroid also needs this fork, I think it's better if its under automattic. What do you think about it?

**Comment by AdamGrzybkowski** [comment]
>What do you think about it?

Sounds good.

**Comment by AdamGrzybkowski** [comment]
@wzieba What would be the best way to have our fork version released?

**Comment by wzieba** [comment]
I think our ~local~ own instance of S3 would be fine. At the same time, it'd be maybe nice to offer this on Maven Central, so the open source community can benefit from your fix from a trusted repository.
