### ISSUE TITLE
QuickEditor: MediaPickerPopup has wrong offset on some devices

### ISSUE THREAD

**Issue by AdamGrzybkowski** [Automattic/Gravatar-SDK-Android#367]
![Image](https://github.com/user-attachments/assets/1f253370-9109-489d-8769-75d8961a90fc)

**Comment by mlumeau** [comment]
@AdamGrzybkowski is this fixed? Can we close the issue?

**Comment by AdamGrzybkowski** [comment]
Yes, not sure why this wasn't closed automatically. 

Closing it now. It was fixed in https://github.com/Automattic/Gravatar-SDK-Android/pull/412

**Comment by AdamGrzybkowski** [comment]
Ohh maybe because it was not merged to trunk.
