### ISSUE TITLE
QuickEditor: Missing action on the Gravatar icon

### ISSUE THREAD

**Issue by AdamGrzybkowski** [Automattic/Gravatar-SDK-Android#376]
When tapped we should show the user profile the same as the `View profile` button.

**Comment by mlumeau** [comment]
To achieve this, we need to propagate the event to the AvatarPicker child component to get the profile URL and move back up to the BottomSheet parent component, and then navigate to a custom tab. 

I think it's a very complex solution to a small problem, we could simplify this a lot by always redirecting to https://gravatar.com/profile, which will be either sign in or profile edition page based on login status in the Web browser.

What do you think?

**Comment by AdamGrzybkowski** [comment]
>To achieve this, we need to propagate the event to the AvatarPicker child component to get the profile URL and move back up to the BottomSheet parent component, and then navigate to a custom tab.


~I don't think you have to do that. You have the state in `ViewModel` including the `Profile` object. So you need to invoke the viewModel on the icon click and then send an action from the ViewModel with the Profile URL.~


Scratch that, the Top bar is higher up. Anyway, I still think we can do it if we use the Email that is passed in `GravatarQuickEditorParams`.
