### ISSUE TITLE
Not catching service functions should throw Gravatar specific exceptions

### ISSUE THREAD

**Issue by AdamGrzybkowski** [Automattic/Gravatar-SDK-Android#377]
There's a difference between catching and non-catching service functions. One returns a specific Gravatar `ErrorType` and the other throws an Exception without any mapping on our side. 

We should consider throwing our own `GravatarException` with `ErrorType`.

**Comment by AdamGrzybkowski** [comment]
@hamorillo thoughts on this one?

**Comment by hamorillo** [comment]
I think we talked about this and decided just to throw the original exception. We can reconsider it, though. 

We are already throwing `HttpException` in some cases. We'll also need to refactor that. However, as a third-party developer, expecting the same kind of exception from the SDK could always be nice.
