### ISSUE TITLE
`Could not find com.github.yalantis:ucrop:2.2.8.`

### ISSUE THREAD

**Issue by wzieba** [Automattic/Gravatar-SDK-Android#81]
### Current behaviour

When adding the SDK to a project, I get `Could not find com.github.yalantis:ucrop:2.2.8.`. 

### Root cause
The configuration requires SDK consumers to declare Jitpack repository in the application to fetch `ucrop` dependency.

### Possible solutions
- IMO, preferable: migrate from Jitpack repository, as it's known for stability and security issues (https://github.com/gradle/gradle/issues/16310#issuecomment-785945980). Maybe we can mirror it to our S3 instance instead?
- Or, at least, we should mention the necessity of having Jitpack repository in the README

**Comment by wzieba** [comment]
2 days ago uCrop merged a PR related to publishing on Maven Central https://github.com/Yalantis/uCrop/pull/907 so we might soon be able to simply drop Jitpack.

**Comment by hamorillo** [comment]
I reviewed this today, and it's not on Maven Central yet.

**Comment by maxme** [comment]
version 2.2.9 was shipped a few days ago but not published to maven central.

**Comment by AdamGrzybkowski** [comment]
We use our fork stored in private s3 so this issue is resolved.

**Comment by richanshah** [comment]
Could not find com.github.yalantis:ucrop:2.2.9.
Required by:
    project :app > project :flutter > project :image_cropper

getting this errrr while using this lib in one of my flutter module

**Comment by wzieba** [comment]
hi @richanshah 👋 This project no longer uses `uCrop` `2.2.9` but instead, `2.2.11`.

Do you mind trying the latest version of Gravatar SDK, [`2.3.1`](https://github.com/Automattic/Gravatar-SDK-Android/releases/tag/2.3.1)?
